language: node_js
node_js:
  - "node"
  - "6"
  - "7"
  - "8"
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - xvfb

cache: yarn

install:
  - cp .env.example .env
  - yarn install

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3; fi # give xvfb some time to start

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn package-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn package-mac; fi